excluded: # paths to ignore during linting. Takes precedence over `included`.
    - Carthage
    - Pods
cyclomatic_complexity:
  warning: 20
  error: 30

disabled_rules:
  - line_length
  - function_body_length
  - identifier_name
  - file_length